package io.github.cotrin8672.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF286A48)
val onPrimaryLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF4E6355)
val onSecondaryLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFF6FBF4)
val onBackgroundLight = Color(0xFF171D19)
val surfaceLight = Color(0xFFF6FBF4)
val onSurfaceLight = Color(0xFF171D19)

val primaryLightMediumContrast = Color(0xFF004D2F)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF33473A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF6FBF4)
val onBackgroundLightMediumContrast = Color(0xFF171D19)
val surfaceLightMediumContrast = Color(0xFFF6FBF4)
val onSurfaceLightMediumContrast = Color(0xFF171D19)

val primaryLightHighContrast = Color(0xFF002816)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF12261B)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF6FBF4)
val onBackgroundLightHighContrast = Color(0xFF171D19)
val surfaceLightHighContrast = Color(0xFFF6FBF4)
val onSurfaceLightHighContrast = Color(0xFF000000)

val primaryDark = Color(0xFF92D5AC)
val onPrimaryDark = Color(0xFF003921)
val secondaryDark = Color(0xFFB5CCBB)
val onSecondaryDark = Color(0xFF213528)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val backgroundDark = Color(0xFF0F1511)
val onBackgroundDark = Color(0xFFDFE4DD)
val surfaceDark = Color(0xFF0F1511)
val onSurfaceDark = Color(0xFFDFE4DD)

val primaryDarkMediumContrast = Color(0xFF96D9B0)
val onPrimaryDarkMediumContrast = Color(0xFF001B0D)
val secondaryDarkMediumContrast = Color(0xFFB9D1BF)
val onSecondaryDarkMediumContrast = Color(0xFF061A0F)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val backgroundDarkMediumContrast = Color(0xFF0F1511)
val onBackgroundDarkMediumContrast = Color(0xFFDFE4DD)
val surfaceDarkMediumContrast = Color(0xFF0F1511)
val onSurfaceDarkMediumContrast = Color(0xFFF7FCF5)

val primaryDarkHighContrast = Color(0xFFEEFFF1)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFEEFFF1)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF0F1511)
val onBackgroundDarkHighContrast = Color(0xFFDFE4DD)
val surfaceDarkHighContrast = Color(0xFF0F1511)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
